# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1997572c897b8ef7e1c1f89b69e86bb7c1a370b393d710767000585f1ee92fdc9c8ccc004a8d7a522f2adc37f974d7735454f09057b9db74e5dc20155e1e3e4d

test:
  secret_key_base: dc8a5192fe36eb0befdc93a1a85dd63dc362ba8dafa49e50ac4c0a679514a12ff6d2321cd589feec61843e7db8d6954c80bec1e6c026d8284085b5d1f8e45c7d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
